server:
port: 8081
spring:
  datasource:
    url: jdbc:mysql://blog.yukinacloud.xyz:3306/college?characterEncoding=utf-8
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
    username: root
    password: root
